
services:
  spring-api1: &app
    build: .
    environment:
      - SERVER_PORT=8080
      - MONGO_URI=mongodb://mongodb:27017/rinhadb?socketTimeoutMS=360000&connectTimeoutMS=360000&maxPoolSize=50&minPoolSize=50
    depends_on:
      - mongodb
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    ports:
      - "8080:8080"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '0.7GB'

  spring-api2:
    <<: *app
    ports:
      - "8090:8090"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.4GB'

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - spring-api1
      - spring-api2
    ports:
      - "9999:9999"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.2GB'

networks:
  app-network: