logging:
  level:
    root: WARN
# localmente use o INFO
#   root: INFO

server:
  compression:
    enabled: true
    min-response-size: 1024
  port: ${SERVER_PORT:8080}
  tomcat:
    connection-timeout : 120000
    max-connections: 1000

spring:
  application:
    name: rinha-backend-2023
  banner:
    location: rinha2023.txt
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGO_URI:mongodb://127.0.0.1:27017/rinhadb?socketTimeoutMS=600000&connectTimeoutMS=600000&maxPoolSize=50&minPoolSize=50}
      writeConcern: UNACKNOWLEDGED
  mvc:
    async:
      request-timeout: 600000